# Generated by Django 3.0 on 2020-08-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmania', '0003_auto_20200821_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='book',
        ),
    ]
